local apply_options = require("settings.utils").apply_options

apply_options({
  clipboard = "unnamedplus",
  completeopt = "menu,menuone,noselect",
  inccommand = "nosplit",
  hidden = true,
  incsearch = true,
  hlsearch = true,
  infercase = true,
  ignorecase = true,
  showtabline = 2,
  cmdheight = 2,
  signcolumn = "yes:1",
  foldlevel = 99,
  termguicolors = true,
  syntax = "on",
  compatible = false,
  cursorline = true,
  autowrite = true,
  splitright = true,
  splitbelow = true,
  autoread = true,
  undodir = "/tmp",
  undolevels = 1000,
  undoreload = 10000,
  tabstop = 2,
  softtabstop = 2,
  shiftwidth = 2,
  expandtab = true,
  smarttab = true,
  autoindent = true,
  backspace = "indent,eol,start",
  complete = ".,w,b,u,t",
  nrformats = "bin,hex",
  ttimeout = true,
  ruler = true,
  laststatus = 2,
  showcmd = true,
  showmode = false,
  wildmenu = true,
  list = true,
  listchars = "trail:·,tab:»-",
  linebreak = true,
  conceallevel = 0,
  sidescrolloff = 5,
  display = "lastline,msgsep",
  wrap = true,
  breakindent = true,
  number = true,
  tabpagemax = 50,
  history = 1000,
  diffopt = "internal,filler,closeoff,vertical",
  nospell = true,
  endofline = true,
  -- Experimental
  cindent = true,
  smartcase = true, -- improve searching using '/'
  smartindent = true, -- smarter indentation
  undofile = true,
  showmatch = true, -- highlight matching [{()}]
  backup = false, -- disable backup
  lazyredraw = true, -- lazyredraw to make macro faster
  startofline = false, -- don't go to the start of the line when moving to another file
  writebackup = false, -- disable backup
  wildignorecase = true,
  wildmode = "longest",
  matchpairs = "(:),{:},[:],<:>", -- highlight match pairs
  omnifunc = "v:lua.vim.lsp.omnifunc",
  encoding = "UTF-8", -- set encoding
  fillchars = "vert:│,fold:·,diff:,msgsep:‾,eob:\\ ,foldopen:▾,foldsep:│,foldclose:▸", -- make vertical split sign better
  shortmess = "filnxtToOFIWc", -- disable some stuff on shortmess -- mine was: filnxtToOFc
  -- shortmess = "filnxtToOFc",
  wildignore = ".lock,.sass-cache,.git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**",
  foldtext = "v:lua.folds_render()",
  foldlevelstart = 99,
  pumheight = 20, -- limit completion items
  re = 0, -- set regexp engine to auto
  scrolloff = 8, -- make scrolling better
  sidescroll = 2, -- make scrolling better
  -- textwidth = 140,
  redrawtime = 10000,
  numberwidth = 2,
  timeoutlen = 1000, -- faster timeout wait time
  updatetime = 300, -- set faster update time
  ttimeoutlen = 300,
  formatoptions = "1jql", -- improve editor formatting
  foldmethod = "expr",
  foldexpr = "nvim_treesitter#foldexpr()",
})
